Repository AngelDiaz591/PI4_Foro_Web, pull requests merged in 2024-05, with the labels that each got.

#62 Follow and feature
  controllers/posts_controller.php
  controllers/users_controller.php
  db/posts/procedures.sql
  models/base.php
  models/database.php
  models/user.php
  public/index.php
  public/resources/js/app.js
  public/resources/js/main.js
  public/resources/js/user.js
  public/resources/stylesheets/components/_spinner.scss
  public/resources/stylesheets/main.css
  public/resources/stylesheets/main.css.map
  public/resources/stylesheets/main.scss
  views/layouts/_header.php
  views/posts/index.php
  views/posts/show.php
  views/users/sessions/show.php
  views/users/show.php
Labels: back-end

#67 fix bugs
  .gitignore
  controllers/application_controller.php
  models/base.php
  public/assets/imgs/.gitignore
  public/index.php
  public/resources/stylesheets/base/_base.scss
  public/resources/stylesheets/layout/_invi.scss
  views/posts/edit.php
  views/posts/index.php
  views/posts/show.php
  views/users/sessions/new.php
Labels: bug

#68 error 500
  models/base.php
  models/post.php
  views/errors/500.php
Labels: bug

#69 Errors Procedures Comments Corrected
  controllers/application_controller.php
  db/comments/procedures.sql
  db/reactions/procedures.sql
  public/resources/css/style.css
  public/resources/img/angry.gif
  public/resources/img/angry.png
  public/resources/img/haha.gif
  public/resources/img/haha.png
  public/resources/img/love.gif
  public/resources/img/love.png
  public/resources/img/sad.gif
  public/resources/img/sad.png
  public/resources/img/thumb.gif
  public/resources/img/thumb.png
  public/resources/img/wow.gif
  public/resources/img/wow.png
  public/resources/js/comments.js
  public/resources/js/reaction.js
Labels: bug

#83 Link unesco themes to posts
  controllers/posts_controller.php
  controllers/unesco_controller.php
  db/db.sql
  db/posts/procedures.sql
  index.php
  models/post.php
  models/unesco.php
  public/index.php
  public/resources/js/app.js
  public/resources/js/comments.js
  public/resources/js/main.js
  public/resources/js/post.js
  public/resources/js/reaction.js
  public/resources/stylesheets/components/_cards.scss
  public/resources/stylesheets/components/_comments.scss
  public/resources/stylesheets/components/_form_posts.scss
  public/resources/stylesheets/components/_nav.scss
  public/resources/stylesheets/main.css
  public/resources/stylesheets/main.css.map
  views/layouts/_sidebar_main.php
  views/posts/index.php
  views/posts/new.php
  views/posts/show.php
Labels: back-end, bug

#89 corrected count reactions
  models/post.php
  public/resources/js/reaction.js
Labels: bug

#88 Syntax Sql correction and minor corrections
  db/reactions/procedures.sql
  views/admins/index.php
  views/posts/index.php
  views/posts/show.php
  views/users/registrations/new.php
Labels: bug

#100 user controll ready
  public/resources/js/useradmin.js
  views/admins/UserManagement.php
Labels: bug

#101 user controll ready and correct conditions for switch and ban user
  controllers/admins_controller.php
  models/admin.php
  models/user.php
  public/resources/js/useradmin.js
  views/admins/UserManagement.php
Labels: back-end, bug

#102 review modal design, and minor changes
  controllers/admins_controller.php
  controllers/posts_controller.php
  public/index.php
  public/resources/js/app.js
  public/resources/stylesheets/abstracts/_variables.scss
  public/resources/stylesheets/components/_cards.scss
  public/resources/stylesheets/main.css
  public/resources/stylesheets/main.css.map
  public/resources/stylesheets/page/_admin.scss
  views/admins/UserManagement.php
  views/admins/reviews.php
  views/admins/topics.php
  views/layouts/_header.php
Labels: front-end

#109 Minor changes
  app/app.php
  app/classes/Autoloader.php
  app/classes/DataBase.php
  app/classes/Router.php
  app/classes/View.php
  app/config.php
  app/controllers/BaseController.php
  app/controllers/ErrorController.php
  app/controllers/HomeController.php
  app/controllers/PostController.php
  app/models/BaseModel.php
  app/models/posts.php
  app/public/.htaccess
  app/public/assets/js/app.js
  app/public/assets/js/errors.js
  app/public/assets/js/posts.js
  app/public/index.php
  app/resources/helpers/application_helper.php
  app/resources/layouts/footer.php
  app/resources/layouts/header.php
  app/resources/views/error/404.view.php
  app/resources/views/home/home.view.php
  app/resources/views/post/edit.view.php
  app/resources/views/post/new.view.php
  app/resources/views/post/show.view.php
  controllers/posts_controller.php
  db/db.sql
  models/post.php
  public/resources/js/user.js
  public/resources/stylesheets/main.css
  public/resources/stylesheets/main.css.map
  public/resources/stylesheets/page/_profile.scss
  views/layouts/_header.php
  views/layouts/_sidebar_main.php
  views/posts/new.php
  views/users/show.php
Labels: bug
